# Generated by Django 2.2 on 2019-05-17 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=25)),
                ('texto', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('S', 'Sigiloso'), ('N', 'Normal'), ('A', 'Administrativo')], max_length=1)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20)),
                ('data_validade', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interessado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(auto_now_add=True)),
                ('cpf', models.CharField(max_length=15)),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.Advogado')),
                ('processo', models.ManyToManyField(to='meuapp.Processo')),
            ],
        ),
        migrations.CreateModel(
            name='Apensamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_apensamento', models.DateField(auto_now_add=True)),
                ('processo_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.Processo')),
            ],
        ),
        migrations.AddField(
            model_name='advogado',
            name='registro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advogados', to='meuapp.Registro'),
        ),
    ]
