# Generated by Django 2.2 on 2019-07-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='contato_bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='justificativa',
            field=models.TextField(null=True),
        ),
    ]
