# Generated by Django 2.2 on 2019-07-16 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfis', '0002_auto_20190715_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='contato_bloqueado',
        ),
        migrations.AddField(
            model_name='perfil',
            name='contatos_bloqueados',
            field=models.ManyToManyField(related_name='usuarios_bloqueados', to=settings.AUTH_USER_MODEL),
        ),
    ]
