# Generated by Django 3.0 on 2019-07-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_bloqueio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_postagem', models.CharField(max_length=300)),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_postagem', to='perfis.Perfil')),
            ],
            options={
                'ordering': ['-data_postagem'],
            },
        ),
    ]
