# Generated by Django 2.2 on 2019-07-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_perfil_bloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
