# Generated by Django 2.2 on 2019-07-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_auto_20190715_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='contatos_bloqueados',
            field=models.ManyToManyField(related_name='usuarios_bloqueados', to='perfis.Perfil'),
        ),
        migrations.DeleteModel(
            name='Bloqueio',
        ),
    ]
