# Generated by Django 2.2 on 2019-07-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_auto_20190715_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='contatos_bloqueados',
        ),
        migrations.AddField(
            model_name='perfil',
            name='contatos_bloqueados',
            field=models.BooleanField(default=False),
        ),
    ]
