# Generated by Django 2.2 on 2019-07-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0005_auto_20190716_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='nome_empresa',
        ),
        migrations.AddField(
            model_name='postagem',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='anexos'),
        ),
    ]
