# Generated by Django 2.2 on 2019-07-16 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0006_auto_20190716_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='imagem',
        ),
    ]
