# Generated by Django 2.2 on 2019-07-17 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0007_remove_postagem_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={},
        ),
    ]
