# Generated by Django 2.2 on 2019-07-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0008_auto_20190716_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={'ordering': ['data_postagem']},
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='ativa',
            new_name='ativo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='justificativa',
        ),
        migrations.AddField(
            model_name='postagem',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/postagens'),
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='contatos_bloqueados',
        ),
        migrations.AddField(
            model_name='perfil',
            name='contatos_bloqueados',
            field=models.ManyToManyField(related_name='_perfil_contatos_bloqueados_+', to='perfis.Perfil'),
        ),
    ]
