# Generated by Django 2.2 on 2019-07-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0009_auto_20190720_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={'ordering': ['-data_postagem']},
        ),
        migrations.AddField(
            model_name='perfil',
            name='melhores_amigos',
            field=models.ManyToManyField(related_name='_perfil_melhores_amigos_+', to='perfis.Perfil'),
        ),
    ]
