# Generated by Django 2.2 on 2019-05-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
